"""empty message

Revision ID: 1872339b91e1
Revises: 5fb2b0991f05
Create Date: 2016-04-28 20:18:09.176438

"""

# revision identifiers, used by Alembic.
revision = '1872339b91e1'
down_revision = '5fb2b0991f05'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('image_filename', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'image_filename')
    ### end Alembic commands ###
