"""empty message

Revision ID: fff99889348a
Revises: 1872339b91e1
Create Date: 2016-04-29 11:50:41.663670

"""

# revision identifiers, used by Alembic.
revision = 'fff99889348a'
down_revision = '1872339b91e1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles_members',
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], )
    )
    op.add_column(u'member', sa.Column('active', sa.String(length=255), nullable=True))
    op.add_column(u'member', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    op.add_column(u'member', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column(u'member', sa.Column('password', sa.String(length=255), nullable=True))
    with op.batch_alter_table('member') as batch_op:
        batch_op.create_unique_constraint('member', ['email'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member') as batch_op:
        batch_op.drop_constraint(None, 'member', type_='unique')
        batch_op.drop_column('password')
        batch_op.drop_column('email')
        batch_op.drop_column('confirmed_at')
        batch_op.drop_column('active')
        op.drop_table('roles_members')
        op.drop_table('role')
    ### end Alembic commands ###
